== Lesemåte

[start=8]
. Stutt _d_ etter sjølvljod eller millom to sjølvljod er for det aller meste daud, d. v. s. burtfallen i talen: ti__d__, stri__d__, lagna__d__, kve__d__a, gle__d__a. Sameleis når han står etter _r_: gar__d__, or__d__.
. I nokre ord kastar dei no den daude __d__'en: _Båe_ to (men: både -- og), _brå_, _breia_, ei _bu_, ei _glo_, _grei-a_, _hei_, _kei_, _lei-a_, _løa_, _snau_, _soleis_ og andre som endar på _leis_, _stø_, _sva_-berg o. fl.
. I bundi form av inkjekyns-ordi (landet, fjellet, huset) er __t__'en daud. Like eins i order _det_. I dei linne inkjekynsordi skriv ein bundi og ubundi form sameleis (eit auge, vistre auga).
. _rn_ vert oftast til _nn_ (dn) i talen: born, kvern, korn. Men det finst bygdemål som hev _rn_, so ein kann bruka den lesemåten og, um ein vil. I bundi form av namnordi er _r_-en burtfallen å kalla. Fyrr skreiv dei _gutarne_, _gjesterne_, _visorne_; ein må lesa _gutane_, _gjestene_, _visone_. No let ein skrifti fylgja talemålet i dette stykket; for __r__-en gjerer ikkje ordi klårare for auga heller. Sjå st. 21–29.
. _g_ og _k_ lyder som _gj_ (_j_) og _kj_ fyre linne sjølvljod (e, i, y, æ, ø, ei, øy): gild, gøyma, kinn, kyrkja. Fyre _e_, _æ_ og _ø_ skriv ein ogso vanleg _j_: gjera, gjæv, kjenne, kjøpa. Men fyre _e_ i _endestavingar_ skriv dei han sjeldan: rike, lykel, dregen.
. Fyre _e_ i samansetning lyder _g_ og _k_ hardt, for di _e_ då står i staden for ein gamall _a_ eller _u_: bakkebrun, vikeblad.
. Ordi fær tonetyngd på to måtar, som me kallar tonelag: einstavingsord hev _einstavings tonelag_: dag´en, bekk´en. Like eins ord som fyrr hev vor einstavings-ord: bøk´er, end´er (av and).
Fleirstavings-ord hev _tostavings tonelag_: vi`sa, so`la seg, dag`ar. Som ein ser, kann ein syna tonelaget med tonelagsteikn, eller aksentar.