== Fyreord til Utgåva 1918

Sidan Ivar Aasen tok til med arbeidet sitt, hev morsmålet vårt fått ei so god dyrking og vyrdsling, både av han sjølv og av andre, at det hev reist seg i ny yngd og friskleik, betre for kvar tid, so det alt no er mykje bøtt på den store målskaden vår.

Den store meisteren og merkesmannen er burte, og alt som levande er i folket bøygjer seg yver gravi hans med takk i hjarta. Både livet og arbeidet hans var so vent og stort at det aldri kann missa makti si, so lenge norsk mål lever og kann halda nordmannshugen vaken og i vokster.

Og no tarv me ikkje berre vona på full atterreising for morsmålet; me må sjå at me hev sigeren i hende å kalla. Det gjeld berre um å halda ut med trugen hug og idig trott, som Aasen og andre hev lært oss.

Aasen "laga" ikkje målformi si; han fann mållovene og synte dei fram, og i skrift retta han seg etter dei ålmennne drag i dei. Best for eit skriftmål er det å ha seg eit breitt læge innimillom bygdemåli, so det i det store og heile kann høva saman med dei alle, og på den vis lett få tilførsla frå dei, leva og nøra seg av dei. Di betre den beste og mest levande tale kann flyta inn i bokmålet, di friskare held det seg.

Dette hadde Ivar Aasen for auga, og han fann, at når skrivemåten retta seg etter dei mest formklåre bygdemål, måtte bokmålet verta best skikka til å samla alle dei andre målføre i landet um seg. Og framvoksteren av det nynorske skriftmål i siste halve hundradåret hev teke den hovudlei som Aasen synte fyre. Det snauaste og lettaste formverk som norsk talemål kjenner, hev skriftmålet vunne seg fram til med umsutsfull temjing og tilsliping, og i alle meir viktuge ting er det den målbunaden som Aasen straks synte fram, so ein må segja at hans syn er godkjent av soga til no.

Men at leitingi etter høvelegaste skriftformi alt skulde vera ende, det var heller ikkje rimeleg; ho kjem truleg til å vara ved endå ei god stund, og det kann ikkje føra anna enn godt med seg, berre me går fram so varsamt og vyrdsamt som det sømer seg når det gjeld so høge og store ting, og når me soleis på serleg måte står framfor åsyni åt soga.
